// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypefwjucpyrkkhzujrbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwZWZ3anVjcHlya2toenVqcmJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDYyNjEsImV4cCI6MjA3NDYyMjI2MX0.7pg46iIg6lyjgxgiaW2h7ZCs1K8Gif9WOIgP9ZePpmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});